In [1]:
import numpy as np
import pandas as pd

In [2]:
City=pd.read_csv('Ahmadabad.csv')

In [3]:
City

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status
0,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished
1,Seller\nVERIFIED OWNER,20000,1080,2,"40,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished
2,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished
3,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished
4,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished
...,...,...,...,...,...,...,...,...,...,...
4755,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished
4756,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished
4757,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished
4758,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished
4759,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished

In [4]:
City['location']=City['Address'].str.split(',').apply(lambda x:x[0])

In [5]:
City['City']=City['Address'].str.split(',').apply(lambda x:x[-1])

In [6]:
City

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,location,City
0,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,Nikol,Ahmedabad
1,Seller\nVERIFIED OWNER,20000,1080,2,"40,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
2,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,Ghodsar,Ahmedabad
3,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
4,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished,Nana Chiloda,Ahmedabad
...,...,...,...,...,...,...,...,...,...,...,...,...
4755,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,Motera,Ahmedabad
4756,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,Prahlad Nagar,Ahmedabad
4757,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
4758,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad
4759,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,Shela,Ahmedabad

In [7]:
City.sample(15)

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,location,City
3877,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
1915,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,Motera,Ahmedabad
1602,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,Ghodsar,Ahmedabad
4123,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
4638,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad
4319,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,Shela,Ahmedabad
3887,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,Bopal,Ahmedabad
3285,Seller\nVERIFIED OWNER,25000,1400,2,No Deposit,2 bathrooms,East facing,"Shilaj, Ahmedabad",Shafalya Renown,Furnished,Shilaj,Ahmedabad
984,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished,Nana Chiloda,Ahmedabad
2270,Seller\nVERIFIED OWNER,12000,150,1,"12,000 deposit",1 bathrooms,NaN,"Jodhpur, Ahmedabad",NaN,Semi-Furnished,Jodhpur,Ahmedabad
3627,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,Bopal,Ahmedabad
3514,Seller\nVERIFIED OWNER,2500,150,1,No Deposit,1 bathrooms,NaN,"Mahadev Nagar, Ahmedabad",NaN,Unfurnished,Mahadev Nagar,Ahmedabad
4210,Seller\nVERIFIED OWNER,12000,150,1,"12,000 deposit",1 bathrooms,NaN,"Jodhpur, Ahmedabad",NaN,Semi-Furnished,Jodhpur,Ahmedabad
587,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,Bopal,Ahmedabad
161,Seller\nVERIFIED OWNER,20000,1080,2,"40,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad

In [8]:
City.sample(50)

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,location,City
1975,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,Motera,Ahmedabad
262,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,Ghodsar,Ahmedabad
2170,Seller\nVERIFIED OWNER,12000,150,1,"12,000 deposit",1 bathrooms,NaN,"Jodhpur, Ahmedabad",NaN,Semi-Furnished,Jodhpur,Ahmedabad
2869,Seller\nVERIFIED OWNER,20000,2205,3,No Deposit,4 bathrooms,NaN,"Lambha, Ahmedabad",NaN,Unfurnished,Lambha,Ahmedabad
1749,Seller\nVERIFIED OWNER,20000,2205,3,No Deposit,4 bathrooms,NaN,"Lambha, Ahmedabad",NaN,Unfurnished,Lambha,Ahmedabad
1685,Seller\nVERIFIED OWNER,25000,1400,2,No Deposit,2 bathrooms,East facing,"Shilaj, Ahmedabad",Shafalya Renown,Furnished,Shilaj,Ahmedabad
3360,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,Nikol,Ahmedabad
2898,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad
1528,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,Chandkheda,Ahmedabad
3223,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
1969,Seller\nVERIFIED OWNER,20000,2205,3,No Deposit,4 bathrooms,NaN,"Lambha, Ahmedabad",NaN,Unfurnished,Lambha,Ahmedabad
1099,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,Shela,Ahmedabad
4678,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad
4652,Seller\nVERIFIED OWNER,40000,2250,3,"80,000 deposit",4 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Semi-Furnished,Bopal,Ahmedabad
806,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Memnagar, Ahmedabad",Satyam Skyline II,Furnished,Memnagar,Ahmedabad
828,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,Chandkheda,Ahmedabad
2828,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,Chandkheda,Ahmedabad
4373,Seller\nVERIFIED OWNER,15000,1125,2,"30,000 deposit",2 bathrooms,NaN,"Hatkeshwar, Ahmedabad",NaN,Semi-Furnished,Hatkeshwar,Ahmedabad
415,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,Motera,Ahmedabad
951,Seller\nVERIFIED OWNER,45000,1200,3,"90,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",Artham 41,Furnished,Chandkheda,Ahmedabad
687,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,Bopal,Ahmedabad
4728,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,Chandkheda,Ahmedabad
2218,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad
4060,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,Nikol,Ahmedabad
3928,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,Chandkheda,Ahmedabad
4374,Seller\nVERIFIED OWNER,2500,150,1,No Deposit,1 bathrooms,NaN,"Mahadev Nagar, Ahmedabad",NaN,Unfurnished,Mahadev Nagar,Ahmedabad
4247,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,Bopal,Ahmedabad
2931,Seller\nVERIFIED OWNER,45000,1200,3,"90,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",Artham 41,Furnished,Chandkheda,Ahmedabad
255,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,Motera,Ahmedabad
976,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,Prahlad Nagar,Ahmedabad
71,Seller\nVERIFIED OWNER,45000,1200,3,"90,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",Artham 41,Furnished,Chandkheda,Ahmedabad
4457,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
459,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,Shela,Ahmedabad
1357,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
1798,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad
2730,Seller\nVERIFIED OWNER,12000,150,1,"12,000 deposit",1 bathrooms,NaN,"Jodhpur, Ahmedabad",NaN,Semi-Furnished,Jodhpur,Ahmedabad
3404,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished,Nana Chiloda,Ahmedabad
1393,Seller\nVERIFIED OWNER,15000,1125,2,"30,000 deposit",2 bathrooms,NaN,"Hatkeshwar, Ahmedabad",NaN,Semi-Furnished,Hatkeshwar,Ahmedabad
1960,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,Nikol,Ahmedabad
2229,Seller\nVERIFIED OWNER,20000,2205,3,No Deposit,4 bathrooms,NaN,"Lambha, Ahmedabad",NaN,Unfurnished,Lambha,Ahmedabad
2683,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
1737,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
1296,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,Prahlad Nagar,Ahmedabad
1603,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
3137,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
768,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,Chandkheda,Ahmedabad
4111,Seller\nVERIFIED OWNER,45000,1200,3,"90,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",Artham 41,Furnished,Chandkheda,Ahmedabad
3609,Seller\nVERIFIED OWNER,20000,2205,3,No Deposit,4 bathrooms,NaN,"Lambha, Ahmedabad",NaN,Unfurnished,Lambha,Ahmedabad
437,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
2992,Seller\nVERIFIED OWNER,40000,2250,3,"80,000 deposit",4 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Semi-Furnished,Bopal,Ahmedabad

In [9]:
## conversion of rentcolumn into numeric type:
def convert_rent(rent):
    if "L" in rent:
        return int(float(rent.replace('L','').replace(',','').strip())*100000)                                           
    else:
        return int(float(rent.replace(',','').strip()))

In [10]:
def Convert_rent(rent):
    # Check if the input is an integer, and handle it directly
    if isinstance(rent, int):
        return rent
    
    # Ensure the input is a string before using string operations
    if isinstance(rent, str):
        if "L" in rent:
            return int(float(rent.replace('L', '').replace(',', '').strip()) * 100000)
        else:
            return int(rent.replace(',', '').strip())
    
    # Handle unexpected types (e.g., NaN, None)
    return None

In [11]:
City['Rent']=City['Rent'].apply(Convert_rent)

In [12]:
City

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,location,City
0,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,Nikol,Ahmedabad
1,Seller\nVERIFIED OWNER,20000,1080,2,"40,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
2,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,Ghodsar,Ahmedabad
3,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad
4,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished,Nana Chiloda,Ahmedabad
...,...,...,...,...,...,...,...,...,...,...,...,...
4755,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,Motera,Ahmedabad
4756,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,Prahlad Nagar,Ahmedabad
4757,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad
4758,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad
4759,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,Shela,Ahmedabad

In [13]:
City['Rent']=City['Rent'].astype(int)

In [14]:
City.dtypes

broker_consultancy    object
Rent                   int64
Area                   int64
appartment_type        int64
Deposit               object
Bathrooms             object
Facing                object
Address               object
Apartment Name        object
Status                object
location              object
City                  object
dtype: object

In [15]:
City['Rent/sqfit']=City['Rent']/City['Area']

In [16]:
City

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,location,City,Rent/sqfit
0,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,Nikol,Ahmedabad,22.500000
1,Seller\nVERIFIED OWNER,20000,1080,2,"40,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad,18.518519
2,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,Ghodsar,Ahmedabad,31.460674
3,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,Maninagar,Ahmedabad,10.000000
4,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished,Nana Chiloda,Ahmedabad,13.636364
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4755,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,Motera,Ahmedabad,20.000000
4756,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,Prahlad Nagar,Ahmedabad,23.076923
4757,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,Chandkheda,Ahmedabad,14.166667
4758,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,Motera,Ahmedabad,16.000000
4759,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,Shela,Ahmedabad,15.555556

In [37]:
City.sample(150)

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,location,City,Rent/sqfit
2563,Seller\nVERIFIED OWNER,80000,3105,3,No Deposit,3 bathrooms,NaN,"Nanakramguda, Hyderabad",Trend Set Trendset Winz,Furnished,Nanakramguda,Hyderabad,25.764895
8548,Individual Agent\nAGENT\n0,25000,1350,2,No Deposit,2 bathrooms,NaN,"Nallagandla Gachibowli, Hyderabad",NaN,Semi-Furnished,Nallagandla Gachibowli,Hyderabad,18.518519
6012,SYNERGY CONSULTANTS\nAGENT\n0,42000,1886,3,No Deposit,3 bathrooms,NaN,"Nanakramguda, Hyderabad",Pacifica Hillcrest,Unfurnished,Nanakramguda,Hyderabad,22.269353
3529,Ishaan\nAGENT\n-,50000,2050,3,No Deposit,3 bathrooms,East facing,"Shaikpet, Hyderabad",NaN,Semi-Furnished,Shaikpet,Hyderabad,24.390244
4218,VENKY\nAGENT\n-,15000,1000,1,No Deposit,1 bathrooms,NaN,"Kondapur, Hyderabad",NaN,Semi-Furnished,Kondapur,Hyderabad,15.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2174,Thirupathi Rentals\nAGENT\n-,17000,650,1,No Deposit,1 bathrooms,East facing,"Kondapur, Hyderabad",NaN,Semi-Furnished,Kondapur,Hyderabad,26.153846
4657,SG RENTALS\nAGENT\n0,30000,1200,2,No Deposit,2 bathrooms,NaN,"Kondapur, Hyderabad",NaN,Semi-Furnished,Kondapur,Hyderabad,25.000000
8546,Seller\nVERIFIED OWNER,20000,1800,3,No Deposit,3 bathrooms,NaN,"Uppal, Hyderabad",NaN,Furnished,Uppal,Hyderabad,11.111111
2697,SG RENTALS\nAGENT\n-,30000,1200,2,No Deposit,2 bathrooms,NaN,"Kondapur, Hyderabad",NaN,Semi-Furnished,Kondapur,Hyderabad,25.000000
4967,Asif\nAGENT\n0,114999,3130,3,No Deposit,3 bathrooms,NaN,"Banjara Hills, Hyderabad",Dream Valencia,Semi-Furnished,Banjara Hills,Hyderabad,36.740895

In [17]:
City.describe()

               Rent         Area  appartment_type   Rent/sqfit
count   4760.000000  4760.000000       4760.00000  4760.000000
mean   23390.000000  1345.250000          2.35000    21.559842
std    11470.071455   723.803322          1.06195    14.988461
min     2500.000000   150.000000          1.00000     9.070295
25%    15000.000000   972.500000          1.75000    14.034091
50%    20000.000000  1225.000000          2.00000    17.817460
75%    28500.000000  1800.000000          3.00000    22.644231
max    48000.000000  3000.000000          5.00000    80.000000

In [18]:
filtered_city = City[City['Rent/sqfit'] <=15]

In [19]:
filtered_city.location.unique()

array(['Maninagar', 'Nana Chiloda', 'Chandkheda', 'Lambha', 'Hatkeshwar'],
      dtype=object)

In [20]:
filtered_city1 = City[(City['Rent/sqfit'] > 15) & (City['Rent/sqfit'] <=20)]

In [21]:
filtered_city1.location.unique()

array(['Maninagar', 'Shilaj', 'Bopal', 'Mahadev Nagar', 'Motera', 'Shela'],
      dtype=object)

In [22]:
filtered_city2 = City[City['Rent/sqfit'] >20]

In [23]:
filtered_city2.location.unique()

array(['Nikol', 'Ghodsar', 'Memnagar', 'Jodhpur', 'Chandkheda',
       'Prahlad Nagar'], dtype=object)

In [24]:
City.drop(columns=['location'],inplace=True)

In [25]:
City.drop(columns=['City'],inplace=True)

In [26]:
def add_rent_class(df):
    """
    Adds a 'class' column to the DataFrame based on the 'Rent/sqft' values.
    
    Parameters:
    df (pd.DataFrame): The DataFrame to which the 'class' column will be added.
    
    Returns:
    pd.DataFrame: The DataFrame with the new 'class' column.
    """
    def classify_rent(rent_sqfit):
        if rent_sqfit <= 15:
            return 'class3'
        elif 15 <= rent_sqfit <= 20:
            return 'class2'
        else:
            return 'class1'
    
    df['class'] = df['Rent/sqfit'].apply(classify_rent)
    return df

In [27]:
city_with_class = add_rent_class(City)

In [28]:
city_with_class

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,Rent/sqfit,class
0,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,22.500000,class1
1,Seller\nVERIFIED OWNER,20000,1080,2,"40,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,18.518519,class2
2,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,31.460674,class1
3,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,10.000000,class3
4,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished,13.636364,class3
...,...,...,...,...,...,...,...,...,...,...,...,...
4755,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,20.000000,class2
4756,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,23.076923,class1
4757,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,14.166667,class3
4758,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,16.000000,class2
4759,City Estate Management\nAGENT\n0,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,15.555556,class2

In [29]:
city_with_class.sample(150)

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,Rent/sqfit,class
2167,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,20.000000,class2
2811,Seller\nVERIFIED OWNER,45000,1200,3,"90,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",Artham 41,Furnished,37.500000,class1
1200,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,22.500000,class1
2618,Daata Real Estate\nAGENT\n0,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,16.000000,class2
2742,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,31.460674,class1
...,...,...,...,...,...,...,...,...,...,...,...,...
1467,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,20.000000,class2
4752,Seller\nVERIFIED OWNER,40000,2250,3,"80,000 deposit",4 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Semi-Furnished,17.777778,class2
1168,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,11.000000,class3
2316,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,23.076923,class1
952,Seller\nVERIFIED OWNER,40000,2250,3,"80,000 deposit",4 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Semi-Furnished,17.777778,class2

In [30]:
city_with_class.head(20)

,broker_consultancy,Rent,Area,appartment_type,Deposit,Bathrooms,Facing,Address,Apartment Name,Status,Rent/sqfit,class
0,Seller\nVERIFIED OWNER,27000,1200,3,"85,000 deposit",3 bathrooms,NaN,"Nikol, Ahmedabad",NaN,Semi-Furnished,22.500000,class1
1,Seller\nVERIFIED OWNER,20000,1080,2,"40,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,18.518519,class2
2,Seller\nVERIFIED OWNER,14000,445,1,No Deposit,1 bathrooms,NaN,"Ghodsar, Ahmedabad",NaN,Semi-Furnished,31.460674,class1
3,Seller\nVERIFIED OWNER,13500,1350,2,"27,000 deposit",2 bathrooms,NaN,"Maninagar, Ahmedabad",NaN,Furnished,10.000000,class3
4,Seller\nVERIFIED OWNER,30000,2200,5,"60,000 deposit",5 bathrooms,NaN,"Nana Chiloda, Ahmedabad",NaN,Furnished,13.636364,class3
5,Seller\nVERIFIED OWNER,25000,1400,2,No Deposit,2 bathrooms,East facing,"Shilaj, Ahmedabad",Shafalya Renown,Furnished,17.857143,class2
6,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Memnagar, Ahmedabad",Satyam Skyline II,Furnished,23.076923,class1
7,Seller\nVERIFIED OWNER,25000,1250,3,"50,000 deposit",3 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Unfurnished,20.000000,class2
8,Seller\nVERIFIED OWNER,19800,1800,2,No Deposit,2 bathrooms,East facing,"Chandkheda, Ahmedabad",NaN,Furnished,11.000000,class3
9,Seller\nVERIFIED OWNER,20000,2205,3,No Deposit,4 bathrooms,NaN,"Lambha, Ahmedabad",NaN,Unfurnished,9.070295,class3
10,Seller\nVERIFIED OWNER,12000,150,1,"12,000 deposit",1 bathrooms,NaN,"Jodhpur, Ahmedabad",NaN,Semi-Furnished,80.000000,class1
11,Seller\nVERIFIED OWNER,45000,1200,3,"90,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",Artham 41,Furnished,37.500000,class1
12,Seller\nVERIFIED OWNER,40000,2250,3,"80,000 deposit",4 bathrooms,NaN,"Bopal, Ahmedabad",NaN,Semi-Furnished,17.777778,class2
13,Seller\nVERIFIED OWNER,15000,1125,2,"30,000 deposit",2 bathrooms,NaN,"Hatkeshwar, Ahmedabad",NaN,Semi-Furnished,13.333333,class3
14,Seller\nVERIFIED OWNER,2500,150,1,No Deposit,1 bathrooms,NaN,"Mahadev Nagar, Ahmedabad",NaN,Unfurnished,16.666667,class2
15,Seller\nVERIFIED OWNER,36000,1800,3,1 L deposit,3 bathrooms,NaN,"Motera, Ahmedabad",Swagat Bungalows 3,Furnished,20.000000,class2
16,Seller\nVERIFIED OWNER,15000,650,1,No Deposit,1 bathrooms,East facing,"Prahlad Nagar, Ahmedabad",Goyal Riviera Blues,Furnished,23.076923,class1
17,Seller\nVERIFIED OWNER,17000,1200,3,"34,000 deposit",3 bathrooms,NaN,"Chandkheda, Ahmedabad",NaN,Semi-Furnished,14.166667,class3
18,Daata Real Estate\nAGENT\n-,48000,3000,2,No Deposit,2 bathrooms,West facing,"Motera, Ahmedabad",Dwarkesh Radiance,Furnished,16.000000,class2
19,City Estate Management\nAGENT\n-,28000,1800,4,No Deposit,4 bathrooms,NorthEast facing,"Shela, Ahmedabad",Siddheshwar Bungalows,Unfurnished,15.555556,class2

In [31]:
city_with_class.to_csv('Ahmadabad_class.csv', index=False)